## 并发

1. 多个 goroutine 同时操作一个资源就会发生竞态问题
   - 经典的累加问题: **值覆盖**
2. 互斥锁: `sync.Mutex`

   - 多个 goroutine 同时等待一个锁时, 唤醒的策略是随机的

3. 读写互斥锁: `sync.RWMutex`

   - Lock(): 写锁
   - Unlock(): 释放写锁
   - RLock(): 读锁
   - RUnlock():释放读锁

4. 等待组: `sync.WaitGroup`{java-cdl}

   - Add(int)
   - Done()
   - Wait()

5. 并发控制一次: `sync.Once`{java-单例-dcl}

   - `func (o *Once) Do(f func())`
   - sync.Once 其实内部包含一个互斥锁和一个布尔值
   - 互斥锁保证布尔值和数据的安全
   - 而布尔值用来记录初始化是否完成

6. sync.Map

   - 多个 goroutine 操作同一个 Map 线程不安全
   - Store(key, value interface{})
   - Load(key interface{}) (value interface{}, ok bool)
   - Delete(key interface{})
   - **`Range(f func(key, value interface{}) bool)`**: {java-map()}

7. 原子操作

   - pkg: `sync/atomic`
   - sample

     ```go
     // 原子操作版
     type AtomicCounter struct {
       counter int64
     }

     func (a *AtomicCounter) Inc() {
       atomic.AddInt64(&a.counter, 1)
     }

     func (a *AtomicCounter) Load() int64 {
       return atomic.LoadInt64(&a.counter)
     }
     ```

## 并发错误处理

1. 开启 goroutine 去并发地执行任务很简单, 但是对于的并发错误处理很困难
2. defer + recover

   - **panic 只能触发当前 goroutine 的 defer**

   ```go
   go func() {
      defer func() {
         if r := recover(); r != nil {
            fmt.Printf("recover inner panic:%v\n", r)
         }
      }()
      fmt.Println("in goroutine....")
      panic("panic in goroutine")
   }()
   ```

3. errgroup: 批量任务的并发错误处理

   - 为**处理公共任务的子任务而开启的一组 goroutine** `提供` **同步、error 传播和基于 context 的取消功能**
   - `Go(f func() error) || Wait() error`

     ```go
     func fetchUrlDemo2() error {
        g := new(errgroup.Group) // 创建等待组（类似sync.WaitGroup）
        var urls = []string{
           "http://pkg.go.dev",
           "http://www.liwenzhou.com",
           "http://www.yixieqitawangzhi.com",
        }
        for _, url := range urls {
           url := url // 注意此处声明新的变量
           g.Go(func() error {
              resp, err := http.Get(url)
              if err == nil {
                 fmt.Printf("获取%s成功\n", url)
                 resp.Body.Close()
              }
              return err // 返回错误
           })
        }
        if err := g.Wait(); err != nil {
           fmt.Println(err)
           return err
        }
        fmt.Println("所有goroutine均成功")
        return nil
     }
     ```

   - 创建带有 cancel 方法的 errgroup.Group: WithContext
